version: "3"
services:
    oracle:
        image: oracle/database:18.4.0-xe
        volumes:
          - H:/Docker_volumes/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
        ports:
            - "11521:1521"
        environment:
            - ORACLE_PWD=smartedu        